tocollege-net/src/main/java/com/apress/progwt/server/domain/ServerSideUser.java
/*
 * Copyright 2008 Jeff Dwyer
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.apress.progwt.server.domain;

import java.util.Date;

import org.apache.log4j.Logger;
import org.springframework.security.GrantedAuthority;
import org.springframework.security.userdetails.UserDetails;

import com.apress.progwt.client.domain.User;

/**
 * 
 * server side wrapper only. does NOT extend User
 * 
 * @author Jeff Dwyer
 * 
 */
public class ServerSideUser implements UserDetails {

    private static final Logger log = Logger
            .getLogger(ServerSideUser.class);

    private User user;

    public ServerSideUser(User u) {
        this.user = u;
    }

    public GrantedAuthority[] getAuthorities() {
        GrantedAuthority[] rtn = new GrantedAuthority[1];
        if (user.isSupervisor()) {
            log.debug("adding supervisor permissions");
            rtn[0] = new MyAuthority("ROLE_SUPERVISOR");
            return rtn;
        } else {
            rtn[0] = new MyAuthority("");
            return rtn;
        }

    }

    private class MyAuthority implements GrantedAuthority {
        private String auth;

        public MyAuthority(String auth) {
            this.auth = auth;
        }

        public String getAuthority() {
            return auth;
        }

        public int compareTo(Object o) {
            throw new RuntimeException("Unimplemented");
        }
    }

    public String getPassword() {
        return user.getPassword();
    }

    public String getUsername() {
        return user.getUsername();
    }

    public boolean isAccountNonExpired() {
        return user.isAccountNonExpired();
    }

    public boolean isAccountNonLocked() {
        return user.isAccountNonLocked();
    }

    public boolean isCredentialsNonExpired() {
        return user.isCredentialsNonExpired();
    }

    public boolean isEnabled() {
        return user.isEnabled();
    }

    public User getUser() {
        return user;
    }

    public long getId() {
        return user.getId();
    }

    public Date getDateCreated() {
        return user.getDateCreated();
    }

}

tocollege-net/src/main/java/com/apress/progwt/server/web/controllers/MailingListController.java
/*
 * Copyright 2008 Jeff Dwyer
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.apress.progwt.server.web.controllers;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.springframework.validation.BindException;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.SimpleFormController;

import com.apress.progwt.server.service.InvitationService;
import com.apress.progwt.server.web.domain.MailingListCommand;
import com.apress.progwt.server.web.domain.validation.MailingListCommandValidator;

public class MailingListController extends SimpleFormController {
    private static final Logger log = Logger
            .getLogger(MailingListController.class);

    private InvitationService invitationService;

    public MailingListController() {
        setCommandClass(MailingListCommand.class);
        setValidator(new MailingListCommandValidator());
    }

    @Override
    protected ModelAndView onSubmit(HttpServletRequest req,
            HttpServletResponse arg1, Object obj, BindException arg3)
            throws Exception {

        MailingListCommand comm = (MailingListCommand) obj;

        comm.setUserAgent(req.getHeader("User-Agent"));
        comm.setReferer(req.getHeader("Referer"));
        comm.setHost(req.getHeader("Host"));

        log.debug("email: " + comm.getEmail());
        log.debug("user-agent: " + comm.getUserAgent());

        invitationService.requestInvitation(comm);

        String successStr = "Thanks "
                + comm.getEmail()
                + " we'll let you know when you can sign up for an account.";

        Map<String, Object> model = new HashMap<String, Object>();
        model.put("message", successStr);
        model.put("command", new MailingListCommand());

        return new ModelAndView(getSuccessView(), model);

    }

    public void setInvitationService(InvitationService invitationService) {
        this.invitationService = invitationService;
    }

}

tocollege-net/src/main/webapp/WEB-INF/freemarker/secure/extreme/mailinglist.ftl

<#import "/spring.ftl" as spring/>

<html>
  <head>
    <title>Mailing List</title>
  </head>

  <body>
  
  
    
        <#if message?exists>    
            <p class="message">${message}</p>
        </#if>                    
      <div class="main">
    
    <table>
    <tr>
    <th>email</th>
    <th>key</th>    
    <th>inviter</th>    
    <th>signedup</th>    
    <th>mail ok</th>        
    <th></th>
    </tr>

    <#list list as entry>
        <tr>
        <td>${entry.email?default("")}</td>
        <td>${entry.randomkey?default("")}</td>
        <td><#if entry.inviter?exists>${entry.inviter.username}<#else>None</#if></td>
        <td><#if entry.signedUpUser?exists>${entry.signedUpUser.username}<#else>None</#if></td>
        <td>${entry.sentEmailOk?string}</td>
        <td><a href="<@spring.url "/secure/extreme/mailinglistaction.html?entryID=${entry.id?c}"/>"/>Send Invite</a></td>              
        </tr>
    </#list>
    </table>
    
    

    </div>

  </body>
</html>

tocollege-net/src/main/webapp/WEB-INF/freemarker/secure/extreme/scripts.ftl

<#import "/spring.ftl" as spring/>

<html>
  <head>
    <title>Scripts</title>
  </head>

  <body>
  
  
    
        <#if message?exists>    
            <p class="message">${message}</p>
        </#if>                    
      <div class="main">
        <a href="<@spring.url "/secure/extreme/scripts_action_search_index.html"/>"/>Re-Index Search</a>
      </div>

  </body>
</html>